### ISSUE TITLE
AttributeError: 'NMTokens' object has no attribute 'typed_fields_with_attrnames'

### ISSUE THREAD

**Issue by m-harptq** [mitre/stixmarx#10]
Hey there,

We've discovered an error that results from a poor intersection between `stixmarx` and `stix_edh` (see [here](https://github.com/mitre/stix-edh)). When applying `stixmarx.navigator.iterpath()` to STIX packages containing a `xsi:type="edh2cyberMarkingAssert:ISAMarkingsAssertionType"` `<marking:Marking_Structure>` tag like the following:
```
 <stix:Handling>
     <marking:Marking>
         <marking:Controlled_Structure>//node() | //@*</marking:Controlled_Structure>
         <marking:Marking_Structure xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" isam_version="2.0" most_restrictive="true" xsi:type="edh2cyberMarkingAssert:ISAMarkingsAssertionType">
              <edh2:AccessPrivilege>
                  <edh2:privilegeAction>ANONYMOUSACCESS</edh2:privilegeAction>
                  <edh2:privilegeScope>all</edh2:privilegeScope>
                  <edh2:ruleEffect>deny</edh2:ruleEffect>
               </edh2:AccessPrivilege>
         </marking:Marking_Structure>
     </marking:Marking>
</stix:Handling>
```
`stixmarx` will raise the following error:
```
  ...
  File ".../python3.5/site-packages/stixmarx/navigator.py", line 95, in iterpath
    for path_info in yield_and_descend(varname, item):
  File ".../python3.5/site-packages/stixmarx/navigator.py", line 76, in yield_and_descend
    yield (path, attr_name(path, name), item)
  File ".../python3.5/site-packages/stixmarx/utils.py", line 414, in attr_name
    for x in path[-1].typed_fields_with_attrnames():
AttributeError: 'NMTokens' object has no attribute 'typed_fields_with_attrnames'
```
Specifically, the error is raised when walking this tag: `<edh2:privilegeScope>all</edh2:privilegeScope>`. This tag is parsed out as a `NMTokens` class via `stix_edh`. It appears that `stixmarx` demands path objects conform to the `mixbox.entities.Entity` interface and thus supply a `typed_fields_with_attrnames()` method. `NMTokens` does *not*, however, inherit from `mixbox.entities.Entity`, thus raising the AttributeError.

As a simple MonkeyPatch fix on our end, we're dynamically adding `mixbox.entities.Entity` as a base class of `NMTokens`:
```
if Entity not in stix_edh.common.NMTokens.__bases__:
    stix_edh.common.NMTokens.__bases__ += Entity,
```
While this fixes the bug for our purposes and the true cause may be `stix_edh` needing to update their `NMTokens` class, I figured I'd log an issue here as a reliance on `typed_field_with_attrnames()` seems be a bit of a fragile interface.

**Comment by emmanvg** [comment]
Hi @m-harptq. Thanks for the submission! I understand your concern with how `stixmarx` interacts with other objects. This library is purposely designed (tightly coupled) to interact with objects that inherit from `mixbox.entities.Entity`. At this point, my suggestion to solve this would be to look into `stix-edh` and perform the changes there. I could take a look at it, and make a patch release there if appropriate.

**Comment by m-harptq** [comment]
@emmanvg Thanks for the reply! I figured as much, I've opened an issue with `stix_edh` [here](https://github.com/mitre/stix-edh/issues/1). Hopefully they can help shed some light on the situation.

**Comment by emmanvg** [comment]
closing since it has been resolved in the `stix_edh` library.
